# Generated by Django 4.2.4 on 2023-08-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='stock_logos')),
                ('current_value', models.FloatField(max_length=10)),
                ('company_description', models.TextField(max_length=1000)),
                ('founders_name', models.CharField(max_length=100)),
                ('foundation_year', models.IntegerField()),
                ('company_site', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('growth_indicator', models.BooleanField(default=True)),
            ],
        ),
    ]
