# Generated by Django 4.2.4 on 2023-08-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='company_site',
            new_name='company_website',
        ),
        migrations.AddField(
            model_name='stock',
            name='market_change',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='foundation_year',
            field=models.IntegerField(default=0),
        ),
    ]
