# Generated by Django 4.2.4 on 2023-08-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_company_site_stock_company_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='company_description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='company_website',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='founders_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='logo',
            field=models.ImageField(default=None, upload_to='stock_logos'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(default='', max_length=10),
        ),
    ]
