# Generated by Django 4.2.4 on 2023-08-10 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_company_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='')),
                ('date_value', models.DateField()),
                ('close_value', models.FloatField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_chart', to='stock.stock')),
            ],
        ),
    ]
