# Generated by Django 4.2.4 on 2023-08-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_datachart'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayDataStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_value', models.DateField()),
                ('close_value', models.FloatField(default=0)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_data_id', to='stock.stock')),
            ],
        ),
        migrations.DeleteModel(
            name='DataChart',
        ),
    ]
