# Generated by Django 4.2.4 on 2023-08-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_daydatastock_delete_datachart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daydatastock',
            old_name='stock_id',
            new_name='stock',
        ),
    ]
