# Generated by Django 4.2.4 on 2023-08-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stocks_symbols',
            field=models.CharField(default='AAPL,MSFT,GOOG,AMZN,NVDA,META,TSLA,JPM,JNJ,WMT'),
        ),
    ]
