# Generated by Django 4.2.4 on 2023-08-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_remove_user_user_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='daydatastock',
            name='buy_recomendation',
            field=models.CharField(default='Atualize os Dados'),
        ),
    ]
