# Generated by Django 4.2.4 on 2023-08-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_daydatastock_buy_recomendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daydatastock',
            name='buy_recomendation',
        ),
        migrations.AddField(
            model_name='stock',
            name='buy_recomendation',
            field=models.CharField(default='Atualize os Dados'),
        ),
    ]
