# Generated by Django 4.2.4 on 2023-08-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_remove_daydatastock_buy_recomendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daydatastock',
            name='profile_foto',
            field=models.ImageField(blank=True, upload_to='stock_logos'),
        ),
    ]
