# Generated by Django 4.2.4 on 2023-08-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_remove_daydatastock_profile_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daydatastock',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
