# Generated by Django 4.2.4 on 2023-08-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_remove_daydatastock_profile_pic_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='buy_recomendation',
            field=models.CharField(default='Refresh Data'),
        ),
    ]
